# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-22 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirments',
            new_name='Requirements',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='requirments',
            new_name='requirements',
        ),
    ]
