# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-22 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180322_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapiter',
            name='name',
            field=models.CharField(help_text='your chpiter title', max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='pic',
            field=models.URLField(help_text='image link', max_length=1256),
        ),
    ]
