# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-22 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20180322_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pic',
            field=models.CharField(help_text='image link', max_length=1400),
        ),
    ]
