# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-23 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20180322_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pic',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
