# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-25 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20180323_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='facebook_acc',
            field=models.URLField(blank=True, help_text="enter your facebook's link", null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='github_acc',
            field=models.URLField(blank=True, help_text="enter your github's link", null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='instagram_acc',
            field=models.URLField(blank=True, help_text="enter your instagram's link", null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='youtube_acc',
            field=models.URLField(blank=True, help_text="enter your instagram's link", null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='short_summary',
            field=models.CharField(blank=True, help_text='simple and short summary', max_length=80, null=True),
        ),
    ]
