# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-26 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20180325_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='requirment subject (like html)', max_length=150)),
                ('info', models.TextField(help_text='basic info of what should the student learn for this subject ', max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.AlterField(
            model_name='requirements',
            name='name',
            field=models.CharField(help_text='requirment subject (like html)', max_length=150),
        ),
    ]
