# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-26 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20180326_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='authors',
        ),
        migrations.AddField(
            model_name='course',
            name='authors',
            field=models.ForeignKey(help_text='Who are the author of this cource ', null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Authors'),
        ),
    ]
