# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-26 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20180326_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_slug',
            new_name='slug',
        ),
    ]
