# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20180326_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapiter',
            name='chpiterSlug',
        ),
    ]
