# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 23:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0014_chapiter_chpiterslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrolled',
        ),
        migrations.AddField(
            model_name='course',
            name='enrolled',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
