# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 23:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20180328_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrolled',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
