# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-29 05:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0016_auto_20180328_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapiter',
            name='completed',
        ),
        migrations.AddField(
            model_name='chapiter',
            name='completed',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='youtube_links',
            name='seen',
        ),
        migrations.AddField(
            model_name='youtube_links',
            name='seen',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
