# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-29 05:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_auto_20180329_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapiter',
            name='completed',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='youtube_links',
            name='seen',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
