# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-29 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20180329_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_links',
            name='i',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
