# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-29 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_youtube_links_i'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtube_links',
            old_name='i',
            new_name='index',
        ),
        migrations.AddField(
            model_name='chapiter',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Enter the yourtube url playlist', max_length=256, null=True),
        ),
    ]
